title: AGENDA
description: "Private mobile app for task management and personal finances. 100% offline."
url: "https://agenda.omeu.space"
baseurl: ""

# jekyll-polyglot
languages: ["en", "pt"]
default_lang: "en"
exclude_from_localization: ["assets", "CNAME", "feed.xml"]
parallel_localization: false

author:
  name: lizzyman04
  github: https://github.com/lizzyman04/agenda
  email: arlindoabdullm@gmail.com

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: feed.xml
  title: AGENDA Blog

plugins:
  - jekyll-polyglot
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: lizzyman04

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sh"
  - .sass-cache
  - .jekyll-cache
