/// Plain Dart value object representing an ISO 4217 currency.
///
/// No Isar annotation — this is a static data type, not a persisted entity.
class Currency {
  const Currency({
    required this.code,
    required this.name,
    required this.symbol,
  });

  /// ISO 4217 currency code (e.g. 'MZN', 'USD').
  final String code;

  /// Human-readable currency name in English.
  final String name;

  /// Currency symbol for display (e.g. 'MT', r'$', '€').
  final String symbol;
}

/// Static list of ISO 4217 currencies.
///
/// Priority currencies are listed first for Phase 5 picker UI (D-17).
/// All entries are compile-time constants — no network call, no package.
abstract final class Currencies {
  /// Full ISO 4217 currency list. Priority entries appear first.
  /// MZN is always the first entry (app default currency — D-16).
  static const List<Currency> all = [
    // ── Priority entries (D-17) ────────────────────────────────────────────
    Currency(code: 'MZN', name: 'Metical Moçambicano', symbol: 'MT'),
    Currency(code: 'BRL', name: 'Real Brasileiro', symbol: r'R$'),
    Currency(code: 'USD', name: 'US Dollar', symbol: r'$'),
    Currency(code: 'EUR', name: 'Euro', symbol: '€'),
    Currency(code: 'GBP', name: 'British Pound Sterling', symbol: '£'),
    Currency(code: 'JPY', name: 'Japanese Yen', symbol: '¥'),
    Currency(code: 'CAD', name: 'Canadian Dollar', symbol: r'C$'),
    Currency(code: 'AUD', name: 'Australian Dollar', symbol: r'A$'),
    Currency(code: 'CHF', name: 'Swiss Franc', symbol: 'CHF'),
    Currency(code: 'CNY', name: 'Chinese Yuan Renminbi', symbol: '¥'),
    Currency(code: 'ZAR', name: 'South African Rand', symbol: 'R'),
    // ── Remaining ISO 4217 (alphabetical by code) ─────────────────────────
    Currency(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ'),
    Currency(code: 'AFN', name: 'Afghan Afghani', symbol: '؋'),
    Currency(code: 'ALL', name: 'Albanian Lek', symbol: 'L'),
    Currency(code: 'AMD', name: 'Armenian Dram', symbol: '֏'),
    Currency(code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'),
    Currency(code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz'),
    Currency(code: 'ARS', name: 'Argentine Peso', symbol: r'$'),
    Currency(code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ'),
    Currency(code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼'),
    Currency(code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM'),
    Currency(code: 'BBD', name: 'Barbadian Dollar', symbol: r'Bds$'),
    Currency(code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳'),
    Currency(code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв'),
    Currency(code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD'),
    Currency(code: 'BIF', name: 'Burundian Franc', symbol: 'Fr'),
    Currency(code: 'BMD', name: 'Bermudian Dollar', symbol: r'$'),
    Currency(code: 'BND', name: 'Brunei Dollar', symbol: r'B$'),
    Currency(code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.'),
    Currency(code: 'BSD', name: 'Bahamian Dollar', symbol: r'B$'),
    Currency(code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu'),
    Currency(code: 'BWP', name: 'Botswana Pula', symbol: 'P'),
    Currency(code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br'),
    Currency(code: 'BZD', name: 'Belize Dollar', symbol: r'BZ$'),
    Currency(code: 'CDF', name: 'Congolese Franc', symbol: 'Fr'),
    Currency(code: 'CLP', name: 'Chilean Peso', symbol: r'$'),
    Currency(code: 'COP', name: 'Colombian Peso', symbol: r'$'),
    Currency(code: 'CRC', name: 'Costa Rican Colón', symbol: '₡'),
    Currency(code: 'CUP', name: 'Cuban Peso', symbol: r'$'),
    Currency(code: 'CVE', name: 'Cape Verdean Escudo', symbol: r'$'),
    Currency(code: 'CZK', name: 'Czech Koruna', symbol: 'Kč'),
    Currency(code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fr'),
    Currency(code: 'DKK', name: 'Danish Krone', symbol: 'kr'),
    Currency(code: 'DOP', name: 'Dominican Peso', symbol: r'RD$'),
    Currency(code: 'DZD', name: 'Algerian Dinar', symbol: 'دج'),
    Currency(code: 'EGP', name: 'Egyptian Pound', symbol: 'E£'),
    Currency(code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk'),
    Currency(code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br'),
    Currency(code: 'FJD', name: 'Fijian Dollar', symbol: r'FJ$'),
    Currency(code: 'FKP', name: 'Falkland Islands Pound', symbol: '£'),
    Currency(code: 'GEL', name: 'Georgian Lari', symbol: '₾'),
    Currency(code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵'),
    Currency(code: 'GIP', name: 'Gibraltar Pound', symbol: '£'),
    Currency(code: 'GMD', name: 'Gambian Dalasi', symbol: 'D'),
    Currency(code: 'GNF', name: 'Guinean Franc', symbol: 'Fr'),
    Currency(code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q'),
    Currency(code: 'GYD', name: 'Guyanese Dollar', symbol: r'G$'),
    Currency(code: 'HKD', name: 'Hong Kong Dollar', symbol: r'HK$'),
    Currency(code: 'HNL', name: 'Honduran Lempira', symbol: 'L'),
    Currency(code: 'HRK', name: 'Croatian Kuna', symbol: 'kn'),
    Currency(code: 'HTG', name: 'Haitian Gourde', symbol: 'G'),
    Currency(code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft'),
    Currency(code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp'),
    Currency(code: 'ILS', name: 'Israeli New Shekel', symbol: '₪'),
    Currency(code: 'INR', name: 'Indian Rupee', symbol: '₹'),
    Currency(code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د'),
    Currency(code: 'IRR', name: 'Iranian Rial', symbol: '﷼'),
    Currency(code: 'ISK', name: 'Icelandic Króna', symbol: 'kr'),
    Currency(code: 'JMD', name: 'Jamaican Dollar', symbol: r'J$'),
    Currency(code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD'),
    Currency(code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh'),
    Currency(code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'лв'),
    Currency(code: 'KHR', name: 'Cambodian Riel', symbol: '៛'),
    Currency(code: 'KMF', name: 'Comorian Franc', symbol: 'Fr'),
    Currency(code: 'KPW', name: 'North Korean Won', symbol: '₩'),
    Currency(code: 'KRW', name: 'South Korean Won', symbol: '₩'),
    Currency(code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD'),
    Currency(code: 'KYD', name: 'Cayman Islands Dollar', symbol: r'CI$'),
    Currency(code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸'),
    Currency(code: 'LAK', name: 'Lao Kip', symbol: '₭'),
    Currency(code: 'LBP', name: 'Lebanese Pound', symbol: 'L£'),
    Currency(code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs'),
    Currency(code: 'LRD', name: 'Liberian Dollar', symbol: r'L$'),
    Currency(code: 'LSL', name: 'Lesotho Loti', symbol: 'L'),
    Currency(code: 'LYD', name: 'Libyan Dinar', symbol: 'LD'),
    Currency(code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD'),
    Currency(code: 'MDL', name: 'Moldovan Leu', symbol: 'L'),
    Currency(code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar'),
    Currency(code: 'MKD', name: 'Macedonian Denar', symbol: 'ден'),
    Currency(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K'),
    Currency(code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮'),
    Currency(code: 'MOP', name: 'Macanese Pataca', symbol: 'P'),
    Currency(code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM'),
    Currency(code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs'),
    Currency(code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf'),
    Currency(code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK'),
    Currency(code: 'MXN', name: 'Mexican Peso', symbol: r'Mex$'),
    Currency(code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM'),
    Currency(code: 'NAD', name: 'Namibian Dollar', symbol: r'N$'),
    Currency(code: 'NGN', name: 'Nigerian Naira', symbol: '₦'),
    Currency(code: 'NIO', name: 'Nicaraguan Córdoba', symbol: r'C$'),
    Currency(code: 'NOK', name: 'Norwegian Krone', symbol: 'kr'),
    Currency(code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs'),
    Currency(code: 'NZD', name: 'New Zealand Dollar', symbol: r'NZ$'),
    Currency(code: 'OMR', name: 'Omani Rial', symbol: 'R.O.'),
    Currency(code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.'),
    Currency(code: 'PEN', name: 'Peruvian Sol', symbol: 'S/'),
    Currency(code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K'),
    Currency(code: 'PHP', name: 'Philippine Peso', symbol: '₱'),
    Currency(code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs'),
    Currency(code: 'PLN', name: 'Polish Złoty', symbol: 'zł'),
    Currency(code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲'),
    Currency(code: 'QAR', name: 'Qatari Riyal', symbol: 'QR'),
    Currency(code: 'RON', name: 'Romanian Leu', symbol: 'lei'),
    Currency(code: 'RSD', name: 'Serbian Dinar', symbol: 'din'),
    Currency(code: 'RUB', name: 'Russian Ruble', symbol: '₽'),
    Currency(code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr'),
    Currency(code: 'SAR', name: 'Saudi Riyal', symbol: 'SR'),
    Currency(code: 'SBD', name: 'Solomon Islands Dollar', symbol: r'SI$'),
    Currency(code: 'SCR', name: 'Seychellois Rupee', symbol: 'Sr'),
    Currency(code: 'SDG', name: 'Sudanese Pound', symbol: 'LS'),
    Currency(code: 'SEK', name: 'Swedish Krona', symbol: 'kr'),
    Currency(code: 'SGD', name: 'Singapore Dollar', symbol: r'S$'),
    Currency(code: 'SHP', name: 'Saint Helena Pound', symbol: '£'),
    Currency(code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le'),
    Currency(code: 'SOS', name: 'Somali Shilling', symbol: 'Sh'),
    Currency(code: 'SRD', name: 'Surinamese Dollar', symbol: r'SR$'),
    Currency(code: 'SSP', name: 'South Sudanese Pound', symbol: '£'),
    Currency(code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db'),
    Currency(code: 'SVC', name: 'Salvadoran Colón', symbol: '₡'),
    Currency(code: 'SYP', name: 'Syrian Pound', symbol: '£'),
    Currency(code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L'),
    Currency(code: 'THB', name: 'Thai Baht', symbol: '฿'),
    Currency(code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM'),
    Currency(code: 'TMT', name: 'Turkmenistan Manat', symbol: 'T'),
    Currency(code: 'TND', name: 'Tunisian Dinar', symbol: 'DT'),
    Currency(code: 'TOP', name: 'Tongan Paʻanga', symbol: r'T$'),
    Currency(code: 'TRY', name: 'Turkish Lira', symbol: '₺'),
    Currency(code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: r'TT$'),
    Currency(code: 'TWD', name: 'New Taiwan Dollar', symbol: r'NT$'),
    Currency(code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh'),
    Currency(code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴'),
    Currency(code: 'UGX', name: 'Ugandan Shilling', symbol: 'Sh'),
    Currency(code: 'UYU', name: 'Uruguayan Peso', symbol: r'$U'),
    Currency(code: 'UZS', name: 'Uzbekistan Som', symbol: "so'm"),
    Currency(code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S'),
    Currency(code: 'VND', name: 'Vietnamese Đồng', symbol: '₫'),
    Currency(code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt'),
    Currency(code: 'WST', name: 'Samoan Tālā', symbol: 'T'),
    Currency(code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr'),
    Currency(code: 'XCD', name: 'East Caribbean Dollar', symbol: r'EC$'),
    Currency(code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr'),
    Currency(code: 'XPF', name: 'CFP Franc', symbol: 'Fr'),
    Currency(code: 'YER', name: 'Yemeni Rial', symbol: '﷼'),
    Currency(code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK'),
    Currency(code: 'ZWL', name: 'Zimbabwean Dollar', symbol: r'Z$'),
  ];

  /// Priority currency codes — shown first in the Phase 5 picker (D-17).
  static const List<String> priorityCodes = [
    'MZN',
    'BRL',
    'USD',
    'EUR',
    'GBP',
    'JPY',
    'CAD',
    'AUD',
    'CHF',
    'CNY',
    'ZAR',
  ];
}
